"""Game constnts."""
NUMBER_OF_TRY = 3
GAME_EVEN_RANGE = 100
GAME_CALC_FIRST_RANGE = 30
GAME_CALC_SECOND_RANGE = 10
GAME_GCD_FIRST_RANGE = 1000
GAME_GCD_SECOND_RANGE = 100
GAME_PROGRESSION_MAX_START_N = 15
GAME_PROGRESSION_MAX_LEGHT = 15
GAME_PROGRESSION_MAX_STEP = 10
